<div class="news_imc">
        <div class="news_imc_img"><img src="[field:picname/]" width="116" height="85" class="PicAuto" alt="[field:title/]" /></div>
        <div class="news_imc_chaw">
          <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
          <p>　[field:info/]...　</p>
          <h6><a href="[field:arcurl/]" title="查看更多"><img src="/skin/images/ckgg.jpg" width="76" height="14" alt="查看更多" /></a></h6>
        </div>
      </div>