<?php
$z[0]=Array("field","",125,151);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",159,187);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="typename";
$z[3]=Array("field","",227,256);
$z[3][4]['name']="typename";
$z[4]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",343,472);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>