<li class="menu2" onmouseover="this.className=&#39;menu1&#39;" onmouseout="this.className=&#39;menu2&#39;"> <span> <a class="{dede:field.currentstyle/}" href="{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}</a></span>
                <div class="list">
                  <div class="listt"> {dede:channel type='son' noself='yes'} <a href="[field:typeurl/]" title="[field:typename/]">[field:typename/]</a> {/dede:channel} </div>
                </div>
              </li>