<li>
          <div class="imger"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" class="PicAuto" alt="[field:title/]" width="224" height="83" /></a></div>
          <div class="chawr">
            <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
              <div class="c"></div>
            </h4>
            <h6> <em><a href="[field:arcurl/]" title="更多"><img src="/skin/images/gaa.jpg" alt="更多" width="62" height="24" /></a></em> <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></h6>
          </div>
          <div class="c"></div>
        </li>