<li>
          <div class="imger"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" class="PicAuto" alt="[field:title/]" width="173" height="117" /></a></div>
          <div class="chawr">
            <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
              <div class="c"></div>
            </h4>
            <p>[field:description function='cn_substr(@me,170)'/]...　</p>
            <h6><a href="[field:arcurl/]" title="详细信息"><img src="/skin/images/xxf.jpg" width="114" height="28" alt="详细信息" /></a></h6>
          </div>
          <div class="c"></div>
        </li>