<?php
$z[0]=Array("arcurl","",44,59);
$z[1]=Array("title","",68,82);
$z[2]=Array("picname","",94,110);
$z[3]=Array("title","",133,147);
$z[4]=Array("arcurl","",244,259);
$z[5]=Array("title","",268,282);
$z[6]=Array("title","",284,298);
$z[7]=Array("pubdate","",308,355);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("description","",435,485);
$z[8][4]['function']="cn_substr(@me,170)";
$z[9]=Array("arcurl","",522,537);

?>