<?php
$z[0]=Array("channelartlist","\r\n        <li>\r\n          <h4><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h4>\r\n          <p> {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><br />\r\n            {/dede:channel} </p>\r\n        </li>\r\n        ",375,776);
$z[0][4]['typeid']="top";
$z[0][4]['row']="3";
$z[1]=Array("field","",839,868);
$z[1][4]['name']="typename";
$z[2]=Array("global","",1605,1631);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",1689,1713);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",1750,1774);
$z[4][4]['name']="cfg_beian";

?>